#!/bin/env python3
# -*- coding: utf-8 -*-
# encoding=utf-8 vi:ts=4:sw=4:expandtab:ft=python
"""
__init__
"""

# import layercase.sublayer160.Det_cases.cascade_rcnn_cascade_mask_rcnn_r50_fpn_1x_coco
# import layercase.sublayer160.Det_cases.cascade_rcnn_cascade_mask_rcnn_r50_vd_fpn_ssld_1x_coco
# import layercase.sublayer160.Det_cases.cascade_rcnn_cascade_mask_rcnn_r50_vd_fpn_ssld_2x_coco
# import layercase.sublayer160.Det_cases.cascade_rcnn_cascade_rcnn_r50_fpn_1x_coco
# import layercase.sublayer160.Det_cases.cascade_rcnn_cascade_rcnn_r50_vd_fpn_ssld_1x_coco
# import layercase.sublayer160.Det_cases.cascade_rcnn_cascade_rcnn_r50_vd_fpn_ssld_2x_coco
# import layercase.sublayer160.Det_cases.centernet_centernet_mbv3_large_140e_coco
# import layercase.sublayer160.Det_cases.centernet_centernet_mbv3_small_140e_coco
# import layercase.sublayer160.Det_cases.dcn_cascade_rcnn_dcn_r50_fpn_1x_coco
# import layercase.sublayer160.Det_cases.dcn_cascade_rcnn_dcn_x101_vd_64x4d_fpn_1x_coco
# import layercase.sublayer160.Det_cases.dcn_faster_rcnn_dcn_r101_vd_fpn_1x_coco
# import layercase.sublayer160.Det_cases.dcn_faster_rcnn_dcn_r50_fpn_1x_coco
# import layercase.sublayer160.Det_cases.dcn_faster_rcnn_dcn_r50_vd_fpn_1x_coco
# import layercase.sublayer160.Det_cases.dcn_faster_rcnn_dcn_r50_vd_fpn_2x_coco
# import layercase.sublayer160.Det_cases.dcn_faster_rcnn_dcn_x101_vd_64x4d_fpn_1x_coco
# import layercase.sublayer160.Det_cases.dcn_mask_rcnn_dcn_r101_vd_fpn_1x_coco
# import layercase.sublayer160.Det_cases.dcn_mask_rcnn_dcn_r50_fpn_1x_coco
# import layercase.sublayer160.Det_cases.dcn_mask_rcnn_dcn_r50_vd_fpn_2x_coco
# import layercase.sublayer160.Det_cases.dcn_mask_rcnn_dcn_x101_vd_64x4d_fpn_1x_coco
# import layercase.sublayer160.Det_cases.faster_rcnn_faster_rcnn_r101_fpn_2x_coco
# import layercase.sublayer160.Det_cases.faster_rcnn_faster_rcnn_r101_vd_fpn_1x_coco
# import layercase.sublayer160.Det_cases.faster_rcnn_faster_rcnn_r101_vd_fpn_2x_coco
# import layercase.sublayer160.Det_cases.faster_rcnn_faster_rcnn_r34_fpn_1x_coco
# import layercase.sublayer160.Det_cases.faster_rcnn_faster_rcnn_r34_vd_fpn_1x_coco
# import layercase.sublayer160.Det_cases.faster_rcnn_faster_rcnn_r50_fpn_1x_coco
# import layercase.sublayer160.Det_cases.faster_rcnn_faster_rcnn_r50_fpn_2x_coco
# import layercase.sublayer160.Det_cases.faster_rcnn_faster_rcnn_r50_vd_fpn_1x_coco
# import layercase.sublayer160.Det_cases.faster_rcnn_faster_rcnn_r50_vd_fpn_2x_coco
# import layercase.sublayer160.Det_cases.faster_rcnn_faster_rcnn_r50_vd_fpn_ssld_1x_coco
# import layercase.sublayer160.Det_cases.faster_rcnn_faster_rcnn_r50_vd_fpn_ssld_2x_coco
import layercase.sublayer160.Det_cases.faster_rcnn_faster_rcnn_swin_tiny_fpn_1x_coco

# import layercase.sublayer160.Det_cases.faster_rcnn_faster_rcnn_swin_tiny_fpn_2x_coco
# import layercase.sublayer160.Det_cases.faster_rcnn_faster_rcnn_x101_vd_64x4d_fpn_1x_coco
import layercase.sublayer160.Det_cases.faster_rcnn_faster_rcnn_x101_vd_64x4d_fpn_2x_coco

# import layercase.sublayer160.Det_cases.fcos_fcos_dcn_r50_fpn_1x_coco
import layercase.sublayer160.Det_cases.fcos_fcos_r50_fpn_1x_coco

# import layercase.sublayer160.Det_cases.fcos_fcos_r50_fpn_iou_1x_coco
# import layercase.sublayer160.Det_cases.fcos_fcos_r50_fpn_iou_multiscale_2x_coco
# import layercase.sublayer160.Det_cases.fcos_fcos_r50_fpn_multiscale_2x_coco
import layercase.sublayer160.Det_cases.gfl_gfl_r101vd_fpn_mstrain_2x_coco

# import layercase.sublayer160.Det_cases.gfl_gfl_r18vd_1x_coco
# import layercase.sublayer160.Det_cases.gfl_gfl_r34vd_1x_coco
# import layercase.sublayer160.Det_cases.gfl_gfl_r50_fpn_1x_coco
import layercase.sublayer160.Det_cases.gfl_gflv2_r50_fpn_1x_coco

# import layercase.sublayer160.Det_cases.gn_cascade_mask_rcnn_r50_fpn_gn_2x_coco
import layercase.sublayer160.Det_cases.gn_cascade_rcnn_r50_fpn_gn_2x_coco
import layercase.sublayer160.Det_cases.hrnet_faster_rcnn_hrnetv2p_w18_1x_coco

# import layercase.sublayer160.Det_cases.hrnet_faster_rcnn_hrnetv2p_w18_2x_coco
# import layercase.sublayer160.Det_cases.keypoint_higherhrnet_higherhrnet_hrnet_w32_512
import layercase.sublayer160.Det_cases.keypoint_higherhrnet_higherhrnet_hrnet_w32_512_swahr

# import layercase.sublayer160.Det_cases.keypoint_higherhrnet_higherhrnet_hrnet_w32_640
# import layercase.sublayer160.Det_cases.mask_rcnn_mask_rcnn_r101_fpn_1x_coco
# import layercase.sublayer160.Det_cases.mask_rcnn_mask_rcnn_r101_vd_fpn_1x_coco
# import layercase.sublayer160.Det_cases.mask_rcnn_mask_rcnn_r50_fpn_1x_coco
import layercase.sublayer160.Det_cases.mask_rcnn_mask_rcnn_r50_fpn_2x_coco

# import layercase.sublayer160.Det_cases.mask_rcnn_mask_rcnn_r50_vd_fpn_1x_coco
# import layercase.sublayer160.Det_cases.mask_rcnn_mask_rcnn_r50_vd_fpn_2x_coco
# import layercase.sublayer160.Det_cases.mask_rcnn_mask_rcnn_r50_vd_fpn_ssld_1x_coco
# import layercase.sublayer160.Det_cases.mask_rcnn_mask_rcnn_r50_vd_fpn_ssld_2x_coco
# import layercase.sublayer160.Det_cases.mask_rcnn_mask_rcnn_x101_vd_64x4d_fpn_1x_coco
# import layercase.sublayer160.Det_cases.mask_rcnn_mask_rcnn_x101_vd_64x4d_fpn_2x_coco
# import layercase.sublayer160.Det_cases.mot_fairmot_fairmot_dla34_30e_1088x608
# import layercase.sublayer160.Det_cases.mot_fairmot_fairmot_dla34_30e_1088x608_airplane
# import layercase.sublayer160.Det_cases.mot_fairmot_fairmot_dla34_30e_1088x608_bytetracker
# import layercase.sublayer160.Det_cases.mot_fairmot_fairmot_dla34_30e_576x320
# import layercase.sublayer160.Det_cases.mot_fairmot_fairmot_dla34_30e_864x480
# import layercase.sublayer160.Det_cases.mot_fairmot_fairmot_enhance_dla34_60e_1088x608
import layercase.sublayer160.Det_cases.mot_fairmot_fairmot_enhance_hardnet85_30e_1088x608

# import layercase.sublayer160.Det_cases.mot_fairmot_fairmot_hrnetv2_w18_dlafpn_30e_1088x608
# import layercase.sublayer160.Det_cases.mot_fairmot_fairmot_hrnetv2_w18_dlafpn_30e_576x320
# import layercase.sublayer160.Det_cases.mot_fairmot_fairmot_hrnetv2_w18_dlafpn_30e_864x480
# import layercase.sublayer160.Det_cases.mot_headtracking21_fairmot_dla34_30e_1088x608_headtracking21
# import layercase.sublayer160.Det_cases.mot_jde_jde_darknet53_30e_1088x608
# import layercase.sublayer160.Det_cases.mot_jde_jde_darknet53_30e_576x320
import layercase.sublayer160.Det_cases.mot_jde_jde_darknet53_30e_864x480

# import layercase.sublayer160.Det_cases.mot_mcfairmot_mcfairmot_dla34_30e_1088x608_visdrone
# import layercase.sublayer160.Det_cases.mot_mcfairmot_mcfairmot_dla34_30e_1088x608_visdrone_vehicle_bytetracker
import layercase.sublayer160.Det_cases.mot_mcfairmot_mcfairmot_hrnetv2_w18_dlafpn_30e_1088x608_visdrone

# import layercase.sublayer160.Det_cases.mot_mcfairmot_mcfairmot_hrnetv2_w18_dlafpn_30e_1088x608_visdrone_vehicle_bytetracker
# import layercase.sublayer160.Det_cases.mot_mcfairmot_mcfairmot_hrnetv2_w18_dlafpn_30e_576x320_bdd100k_mcmot
# import layercase.sublayer160.Det_cases.mot_mcfairmot_mcfairmot_hrnetv2_w18_dlafpn_30e_576x320_visdrone
# import layercase.sublayer160.Det_cases.mot_mcfairmot_mcfairmot_hrnetv2_w18_dlafpn_30e_864x480_visdrone
import layercase.sublayer160.Det_cases.mot_ocsort_ocsort_ppyoloe

# import layercase.sublayer160.Det_cases.mot_pedestrian_fairmot_dla34_30e_1088x608_pathtrack
# import layercase.sublayer160.Det_cases.mot_pedestrian_fairmot_dla34_30e_1088x608_visdrone_pedestrian
# import layercase.sublayer160.Det_cases.mot_pedestrian_fairmot_hrnetv2_w18_dlafpn_30e_1088x608_visdrone_pedestrian
# import layercase.sublayer160.Det_cases.mot_pedestrian_fairmot_hrnetv2_w18_dlafpn_30e_576x320_visdrone_pedestrian
# import layercase.sublayer160.Det_cases.mot_pedestrian_fairmot_hrnetv2_w18_dlafpn_30e_864x480_visdrone_pedestrian
import layercase.sublayer160.Det_cases.mot_vehicle_fairmot_dla34_30e_1088x608_bdd100kmot_vehicle

# import layercase.sublayer160.Det_cases.mot_vehicle_fairmot_dla34_30e_1088x608_kitti_vehicle
# import layercase.sublayer160.Det_cases.mot_vehicle_fairmot_dla34_30e_1088x608_visdrone_vehicle
# import layercase.sublayer160.Det_cases.mot_vehicle_fairmot_hrnetv2_w18_dlafpn_30e_576x320_bdd100kmot_vehicle
# import layercase.sublayer160.Det_cases.mot_vehicle_fairmot_hrnetv2_w18_dlafpn_30e_576x320_visdrone_vehicle
# import layercase.sublayer160.Det_cases.picodet_legacy_model_more_config_picodet_mobilenetv3_large_1x_416_coco
# import layercase.sublayer160.Det_cases.picodet_legacy_model_picodet_l_320_coco
import layercase.sublayer160.Det_cases.picodet_legacy_model_picodet_l_416_coco

# import layercase.sublayer160.Det_cases.picodet_legacy_model_picodet_l_640_coco
# import layercase.sublayer160.Det_cases.picodet_legacy_model_picodet_m_320_coco
# import layercase.sublayer160.Det_cases.picodet_legacy_model_picodet_m_416_coco
# import layercase.sublayer160.Det_cases.picodet_legacy_model_picodet_s_320_coco
# import layercase.sublayer160.Det_cases.picodet_legacy_model_picodet_s_416_coco
# import layercase.sublayer160.Det_cases.ppyoloe_ppyoloe_crn_l_300e_coco
# import layercase.sublayer160.Det_cases.ppyoloe_ppyoloe_crn_m_300e_coco
# import layercase.sublayer160.Det_cases.ppyoloe_ppyoloe_crn_s_300e_coco
# import layercase.sublayer160.Det_cases.ppyoloe_ppyoloe_crn_s_400e_coco
# import layercase.sublayer160.Det_cases.ppyoloe_ppyoloe_crn_x_300e_coco
# import layercase.sublayer160.Det_cases.ppyoloe_ppyoloe_plus_crn_l_80e_coco
# import layercase.sublayer160.Det_cases.ppyoloe_ppyoloe_plus_crn_m_80e_coco
# import layercase.sublayer160.Det_cases.ppyoloe_ppyoloe_plus_crn_s_80e_coco
# import layercase.sublayer160.Det_cases.ppyoloe_ppyoloe_plus_crn_x_80e_coco
# import layercase.sublayer160.Det_cases.ppyoloe_voc_ppyoloe_plus_crn_l_30e_voc
# import layercase.sublayer160.Det_cases.ppyoloe_voc_ppyoloe_plus_crn_s_30e_voc
# import layercase.sublayer160.Det_cases.ppyolo_ppyolo_mbv3_large_coco
# import layercase.sublayer160.Det_cases.ppyolo_ppyolo_mbv3_small_coco
# import layercase.sublayer160.Det_cases.ppyolo_ppyolo_r50vd_dcn_1x_coco
# import layercase.sublayer160.Det_cases.ppyolo_ppyolo_r50vd_dcn_2x_coco
# import layercase.sublayer160.Det_cases.ppyolo_ppyolo_r50vd_dcn_voc
# import layercase.sublayer160.Det_cases.ppyolo_ppyolo_tiny_650e_coco
import layercase.sublayer160.Det_cases.ppyolo_ppyolov2_r101vd_dcn_365e_coco

# import layercase.sublayer160.Det_cases.ppyolo_ppyolov2_r50vd_dcn_365e_coco
import layercase.sublayer160.Det_cases.rcnn_enhance_faster_rcnn_enhance_3x_coco

# import layercase.sublayer160.Det_cases.res2net_faster_rcnn_res2net50_vb_26w_4s_fpn_1x_coco
# import layercase.sublayer160.Det_cases.res2net_mask_rcnn_res2net50_vb_26w_4s_fpn_2x_coco
# import layercase.sublayer160.Det_cases.res2net_mask_rcnn_res2net50_vd_26w_4s_fpn_2x_coco
import layercase.sublayer160.Det_cases.retinanet_retinanet_r101_distill_r50_2x_coco

# import layercase.sublayer160.Det_cases.retinanet_retinanet_r101_fpn_2x_coco
# import layercase.sublayer160.Det_cases.retinanet_retinanet_r50_fpn_1x_coco
# import layercase.sublayer160.Det_cases.retinanet_retinanet_r50_fpn_2x_coco
import layercase.sublayer160.Det_cases.rotate_fcosr_fcosr_x50_3x_dota
import layercase.sublayer160.Det_cases.rotate_ppyoloe_r_ppyoloe_r_crn_l_3x_dota

# import layercase.sublayer160.Det_cases.rotate_ppyoloe_r_ppyoloe_r_crn_l_3x_dota_ms
# import layercase.sublayer160.Det_cases.rotate_ppyoloe_r_ppyoloe_r_crn_m_3x_dota
# import layercase.sublayer160.Det_cases.rotate_ppyoloe_r_ppyoloe_r_crn_m_3x_dota_ms
# import layercase.sublayer160.Det_cases.rotate_ppyoloe_r_ppyoloe_r_crn_s_3x_dota
# import layercase.sublayer160.Det_cases.rotate_ppyoloe_r_ppyoloe_r_crn_s_3x_dota_ms
# import layercase.sublayer160.Det_cases.rotate_ppyoloe_r_ppyoloe_r_crn_x_3x_dota
# import layercase.sublayer160.Det_cases.rotate_ppyoloe_r_ppyoloe_r_crn_x_3x_dota_ms
# import layercase.sublayer160.Det_cases.rotate_s2anet_s2anet_1x_spine
# import layercase.sublayer160.Det_cases.rotate_s2anet_s2anet_alignconv_2x_dota
import layercase.sublayer160.Det_cases.rotate_s2anet_s2anet_conv_2x_dota

# import layercase.sublayer160.Det_cases.semi_det_baseline_faster_rcnn_r50_fpn_2x_coco_sup010
# import layercase.sublayer160.Det_cases.semi_det_baseline_fcos_r50_fpn_2x_coco_sup005
# import layercase.sublayer160.Det_cases.semi_det_baseline_fcos_r50_fpn_2x_coco_sup010
# import layercase.sublayer160.Det_cases.semi_det_baseline_ppyoloe_plus_crn_s_80e_coco_sup005
# import layercase.sublayer160.Det_cases.semi_det_baseline_ppyoloe_plus_crn_s_80e_coco_sup010
# import layercase.sublayer160.Det_cases.semi_det_baseline_retinanet_r50_fpn_2x_coco_sup010
import layercase.sublayer160.Det_cases.smalldet_ppyoloe_plus_sod_crn_l_80e_coco

# import layercase.sublayer160.Det_cases.sniper_faster_rcnn_r50_fpn_1x_sniper_visdrone
# import layercase.sublayer160.Det_cases.sniper_faster_rcnn_r50_fpn_1x_visdrone
import layercase.sublayer160.Det_cases.solov2_solov2_r101_vd_fpn_3x_coco

# import layercase.sublayer160.Det_cases.solov2_solov2_r50_enhance_coco
import layercase.sublayer160.Det_cases.solov2_solov2_r50_fpn_1x_coco

# import layercase.sublayer160.Det_cases.solov2_solov2_r50_fpn_3x_coco
# import layercase.sublayer160.Det_cases.sparse_rcnn_sparse_rcnn_r50_fpn_3x_pro100_coco
import layercase.sublayer160.Det_cases.sparse_rcnn_sparse_rcnn_r50_fpn_3x_pro300_coco
import layercase.sublayer160.Det_cases.ssd_ssdlite_ghostnet_320_coco

# import layercase.sublayer160.Det_cases.ssd_ssdlite_mobilenet_v3_large_320_coco
import layercase.sublayer160.Det_cases.ssd_ssdlite_mobilenet_v3_small_320_coco
import layercase.sublayer160.Det_cases.ssd_ssd_vgg16_300_240e_voc
import layercase.sublayer160.Det_cases.tood_tood_r50_fpn_1x_coco

# import layercase.sublayer160.Det_cases.ttfnet_pafnet_lite_mobilenet_v3_20x_coco
import layercase.sublayer160.Det_cases.vitdet_ppyoloe_vit_base_csppan_cae_36e_coco

# import layercase.sublayer160.Det_cases.yolov3_yolov3_mobilenet_v1_roadsign
# import layercase.sublayer160.Det_cases.yolov3_yolov3_mobilenet_v3_large_270e_coco
# import layercase.sublayer160.Det_cases.yolov3_yolov3_mobilenet_v3_large_270e_voc
# import layercase.sublayer160.Det_cases.yolov3_yolov3_mobilenet_v3_large_ssld_270e_voc
import layercase.sublayer160.Det_cases.yolox_yolox_cdn_tiny_300e_coco

# import layercase.sublayer160.Det_cases.yolox_yolox_crn_s_300e_coco
# import layercase.sublayer160.Det_cases.yolox_yolox_l_300e_coco
# import layercase.sublayer160.Det_cases.yolox_yolox_m_300e_coco
# import layercase.sublayer160.Det_cases.yolox_yolox_nano_300e_coco
# import layercase.sublayer160.Det_cases.yolox_yolox_s_300e_coco
# import layercase.sublayer160.Det_cases.yolox_yolox_tiny_300e_coco
# import layercase.sublayer160.Det_cases.yolox_yolox_x_300e_coco
