import layercase.sublayer1000.Det_cases.faster_rcnn_faster_rcnn_r50_vd_fpn_2x_coco.SIR_56
import layercase.sublayer1000.Det_cases.faster_rcnn_faster_rcnn_r50_vd_fpn_2x_coco.SIR_49
import layercase.sublayer1000.Det_cases.faster_rcnn_faster_rcnn_r50_vd_fpn_2x_coco.SIR_44
import layercase.sublayer1000.Det_cases.faster_rcnn_faster_rcnn_r50_vd_fpn_2x_coco.SIR_35
import layercase.sublayer1000.Det_cases.faster_rcnn_faster_rcnn_r50_vd_fpn_2x_coco.SIR_55
import layercase.sublayer1000.Det_cases.faster_rcnn_faster_rcnn_r50_vd_fpn_2x_coco.SIR_71
