FROM registry.baidubce.com/paddlepaddle/paddle:latest-dev-cuda11.8-cudnn8.6-trt8.5-gcc82

RUN set -xe && \
    curl -s https://raw.githubusercontent.com/PaddlePaddle/PaddleX/develop/requirements.txt | grep -v -e '^#' -e '^$' > /tmp/requirements_paddlex.txt && \
    curl -s https://raw.githubusercontent.com/PaddlePaddle/PaddleClas/develop/requirements.txt | grep -v -e '^#' -e '^$' > /tmp/requirements_paddleclas.txt && \
    curl -s https://raw.githubusercontent.com/PaddlePaddle/PaddleDetection/develop/requirements.txt | grep -v -e '^#' -e '^$' > /tmp/requirements_paddledetection.txt && \
    curl -s https://raw.githubusercontent.com/PaddlePaddle/PaddleSeg/develop/requirements.txt | grep -v -e '^#' -e '^$' > /tmp/requirements_paddleseg.txt && \
    curl -s https://raw.githubusercontent.com/PaddlePaddle/PaddleOCR/main/requirements.txt | grep -v -e '^#' -e '^$' > /tmp/requirements_paddleocr.txt && \
    python3.10 -m pip install -r /tmp/requirements_paddlex.txt -r /tmp/requirements_paddleclas.txt -r /tmp/requirements_paddledetection.txt -r /tmp/requirements_paddleseg.txt -r /tmp/requirements_paddleocr.txt && \
    python3.10 -m pip cache purge && \
    rm -rf /tmp/requirements_*.txt
RUN apt-get update && apt-get install -y libeigen3-dev libgmp-dev libgmpxx4ldbl libmpfr-dev libboost-dev libboost-thread-dev libtbb-dev python3-dev
RUN wget --no-proxy https://paddle-org.bj.bcebos.com/paddlescience/PyMesh.tar.gz && tar -zxvf PyMesh.tar.gz && \
    cd PyMesh && python3.10 -m pip install -r python/requirements.txt && python3.10 -m pip install -U setuptools && python3.10 setup.py build && python3.10 setup.py install && cd - && rm -rf PyMesh*
