import layercase.Det_cases.rotate_ppyoloe_r_ppyoloe_r_crn_l_3x_dota.SIR_177
import layercase.Det_cases.rotate_ppyoloe_r_ppyoloe_r_crn_l_3x_dota.SIR_167
import layercase.Det_cases.rotate_ppyoloe_r_ppyoloe_r_crn_l_3x_dota.SIR_174
import layercase.Det_cases.rotate_ppyoloe_r_ppyoloe_r_crn_l_3x_dota.SIR_184
