# api:paddle.tensor.manipulation.reshape||api:paddle.tensor.manipulation.split||api:paddle.tensor.linalg.transpose||api:paddle.tensor.linalg.transpose||api:paddle.tensor.linalg.transpose||api:paddle.tensor.linalg.transpose||api:paddle.tensor.linalg.transpose||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||method:__getitem__||api:paddle.tensor.manipulation.gather||api:paddle.tensor.manipulation.concat||api:paddle.tensor.linalg.transpose||method:reshape
import paddle
import unittest
import numpy as np


class LayerCase(paddle.nn.Layer):
    def __init__(self):
        super().__init__()
        self.parameter_0 = self.create_parameter(
           shape=[4, 196],
           dtype=paddle.float32,
        )
    def forward(
        self,
        var_0,    # (shape: [22, 196, 256], dtype: paddle.float32, stop_gradient: False)
        var_1,    # (shape: [196, 196], dtype: paddle.int64, stop_gradient: True)
    ):
        var_2 = paddle.tensor.manipulation.reshape(var_0, [22, 196, 4, 64])
        out = paddle.tensor.manipulation.split(var_2, [16, 16, 32], axis=3)
        var_3 = out[0]
        var_4 = out[1]
        var_5 = out[2]
        var_6 = paddle.tensor.linalg.transpose(var_3, perm=[0, 2, 1, 3])
        var_7 = paddle.tensor.linalg.transpose(var_4, perm=[0, 2, 1, 3])
        var_8 = paddle.tensor.linalg.transpose(var_5, perm=[0, 2, 1, 3])
        var_9 = paddle.tensor.linalg.transpose(var_7, perm=[0, 1, 3, 2])
        var_10 = paddle.tensor.linalg.transpose(self.parameter_0, (1, 0,))
        var_11 = var_1.__getitem__(0)
        var_12 = paddle.tensor.manipulation.gather(var_10, var_11)
        var_13 = var_1.__getitem__(1)
        var_14 = paddle.tensor.manipulation.gather(var_10, var_13)
        var_15 = var_1.__getitem__(2)
        var_16 = paddle.tensor.manipulation.gather(var_10, var_15)
        var_17 = var_1.__getitem__(3)
        var_18 = paddle.tensor.manipulation.gather(var_10, var_17)
        var_19 = var_1.__getitem__(4)
        var_20 = paddle.tensor.manipulation.gather(var_10, var_19)
        var_21 = var_1.__getitem__(5)
        var_22 = paddle.tensor.manipulation.gather(var_10, var_21)
        var_23 = var_1.__getitem__(6)
        var_24 = paddle.tensor.manipulation.gather(var_10, var_23)
        var_25 = var_1.__getitem__(7)
        var_26 = paddle.tensor.manipulation.gather(var_10, var_25)
        var_27 = var_1.__getitem__(8)
        var_28 = paddle.tensor.manipulation.gather(var_10, var_27)
        var_29 = var_1.__getitem__(9)
        var_30 = paddle.tensor.manipulation.gather(var_10, var_29)
        var_31 = var_1.__getitem__(10)
        var_32 = paddle.tensor.manipulation.gather(var_10, var_31)
        var_33 = var_1.__getitem__(11)
        var_34 = paddle.tensor.manipulation.gather(var_10, var_33)
        var_35 = var_1.__getitem__(12)
        var_36 = paddle.tensor.manipulation.gather(var_10, var_35)
        var_37 = var_1.__getitem__(13)
        var_38 = paddle.tensor.manipulation.gather(var_10, var_37)
        var_39 = var_1.__getitem__(14)
        var_40 = paddle.tensor.manipulation.gather(var_10, var_39)
        var_41 = var_1.__getitem__(15)
        var_42 = paddle.tensor.manipulation.gather(var_10, var_41)
        var_43 = var_1.__getitem__(16)
        var_44 = paddle.tensor.manipulation.gather(var_10, var_43)
        var_45 = var_1.__getitem__(17)
        var_46 = paddle.tensor.manipulation.gather(var_10, var_45)
        var_47 = var_1.__getitem__(18)
        var_48 = paddle.tensor.manipulation.gather(var_10, var_47)
        var_49 = var_1.__getitem__(19)
        var_50 = paddle.tensor.manipulation.gather(var_10, var_49)
        var_51 = var_1.__getitem__(20)
        var_52 = paddle.tensor.manipulation.gather(var_10, var_51)
        var_53 = var_1.__getitem__(21)
        var_54 = paddle.tensor.manipulation.gather(var_10, var_53)
        var_55 = var_1.__getitem__(22)
        var_56 = paddle.tensor.manipulation.gather(var_10, var_55)
        var_57 = var_1.__getitem__(23)
        var_58 = paddle.tensor.manipulation.gather(var_10, var_57)
        var_59 = var_1.__getitem__(24)
        var_60 = paddle.tensor.manipulation.gather(var_10, var_59)
        var_61 = var_1.__getitem__(25)
        var_62 = paddle.tensor.manipulation.gather(var_10, var_61)
        var_63 = var_1.__getitem__(26)
        var_64 = paddle.tensor.manipulation.gather(var_10, var_63)
        var_65 = var_1.__getitem__(27)
        var_66 = paddle.tensor.manipulation.gather(var_10, var_65)
        var_67 = var_1.__getitem__(28)
        var_68 = paddle.tensor.manipulation.gather(var_10, var_67)
        var_69 = var_1.__getitem__(29)
        var_70 = paddle.tensor.manipulation.gather(var_10, var_69)
        var_71 = var_1.__getitem__(30)
        var_72 = paddle.tensor.manipulation.gather(var_10, var_71)
        var_73 = var_1.__getitem__(31)
        var_74 = paddle.tensor.manipulation.gather(var_10, var_73)
        var_75 = var_1.__getitem__(32)
        var_76 = paddle.tensor.manipulation.gather(var_10, var_75)
        var_77 = var_1.__getitem__(33)
        var_78 = paddle.tensor.manipulation.gather(var_10, var_77)
        var_79 = var_1.__getitem__(34)
        var_80 = paddle.tensor.manipulation.gather(var_10, var_79)
        var_81 = var_1.__getitem__(35)
        var_82 = paddle.tensor.manipulation.gather(var_10, var_81)
        var_83 = var_1.__getitem__(36)
        var_84 = paddle.tensor.manipulation.gather(var_10, var_83)
        var_85 = var_1.__getitem__(37)
        var_86 = paddle.tensor.manipulation.gather(var_10, var_85)
        var_87 = var_1.__getitem__(38)
        var_88 = paddle.tensor.manipulation.gather(var_10, var_87)
        var_89 = var_1.__getitem__(39)
        var_90 = paddle.tensor.manipulation.gather(var_10, var_89)
        var_91 = var_1.__getitem__(40)
        var_92 = paddle.tensor.manipulation.gather(var_10, var_91)
        var_93 = var_1.__getitem__(41)
        var_94 = paddle.tensor.manipulation.gather(var_10, var_93)
        var_95 = var_1.__getitem__(42)
        var_96 = paddle.tensor.manipulation.gather(var_10, var_95)
        var_97 = var_1.__getitem__(43)
        var_98 = paddle.tensor.manipulation.gather(var_10, var_97)
        var_99 = var_1.__getitem__(44)
        var_100 = paddle.tensor.manipulation.gather(var_10, var_99)
        var_101 = var_1.__getitem__(45)
        var_102 = paddle.tensor.manipulation.gather(var_10, var_101)
        var_103 = var_1.__getitem__(46)
        var_104 = paddle.tensor.manipulation.gather(var_10, var_103)
        var_105 = var_1.__getitem__(47)
        var_106 = paddle.tensor.manipulation.gather(var_10, var_105)
        var_107 = var_1.__getitem__(48)
        var_108 = paddle.tensor.manipulation.gather(var_10, var_107)
        var_109 = var_1.__getitem__(49)
        var_110 = paddle.tensor.manipulation.gather(var_10, var_109)
        var_111 = var_1.__getitem__(50)
        var_112 = paddle.tensor.manipulation.gather(var_10, var_111)
        var_113 = var_1.__getitem__(51)
        var_114 = paddle.tensor.manipulation.gather(var_10, var_113)
        var_115 = var_1.__getitem__(52)
        var_116 = paddle.tensor.manipulation.gather(var_10, var_115)
        var_117 = var_1.__getitem__(53)
        var_118 = paddle.tensor.manipulation.gather(var_10, var_117)
        var_119 = var_1.__getitem__(54)
        var_120 = paddle.tensor.manipulation.gather(var_10, var_119)
        var_121 = var_1.__getitem__(55)
        var_122 = paddle.tensor.manipulation.gather(var_10, var_121)
        var_123 = var_1.__getitem__(56)
        var_124 = paddle.tensor.manipulation.gather(var_10, var_123)
        var_125 = var_1.__getitem__(57)
        var_126 = paddle.tensor.manipulation.gather(var_10, var_125)
        var_127 = var_1.__getitem__(58)
        var_128 = paddle.tensor.manipulation.gather(var_10, var_127)
        var_129 = var_1.__getitem__(59)
        var_130 = paddle.tensor.manipulation.gather(var_10, var_129)
        var_131 = var_1.__getitem__(60)
        var_132 = paddle.tensor.manipulation.gather(var_10, var_131)
        var_133 = var_1.__getitem__(61)
        var_134 = paddle.tensor.manipulation.gather(var_10, var_133)
        var_135 = var_1.__getitem__(62)
        var_136 = paddle.tensor.manipulation.gather(var_10, var_135)
        var_137 = var_1.__getitem__(63)
        var_138 = paddle.tensor.manipulation.gather(var_10, var_137)
        var_139 = var_1.__getitem__(64)
        var_140 = paddle.tensor.manipulation.gather(var_10, var_139)
        var_141 = var_1.__getitem__(65)
        var_142 = paddle.tensor.manipulation.gather(var_10, var_141)
        var_143 = var_1.__getitem__(66)
        var_144 = paddle.tensor.manipulation.gather(var_10, var_143)
        var_145 = var_1.__getitem__(67)
        var_146 = paddle.tensor.manipulation.gather(var_10, var_145)
        var_147 = var_1.__getitem__(68)
        var_148 = paddle.tensor.manipulation.gather(var_10, var_147)
        var_149 = var_1.__getitem__(69)
        var_150 = paddle.tensor.manipulation.gather(var_10, var_149)
        var_151 = var_1.__getitem__(70)
        var_152 = paddle.tensor.manipulation.gather(var_10, var_151)
        var_153 = var_1.__getitem__(71)
        var_154 = paddle.tensor.manipulation.gather(var_10, var_153)
        var_155 = var_1.__getitem__(72)
        var_156 = paddle.tensor.manipulation.gather(var_10, var_155)
        var_157 = var_1.__getitem__(73)
        var_158 = paddle.tensor.manipulation.gather(var_10, var_157)
        var_159 = var_1.__getitem__(74)
        var_160 = paddle.tensor.manipulation.gather(var_10, var_159)
        var_161 = var_1.__getitem__(75)
        var_162 = paddle.tensor.manipulation.gather(var_10, var_161)
        var_163 = var_1.__getitem__(76)
        var_164 = paddle.tensor.manipulation.gather(var_10, var_163)
        var_165 = var_1.__getitem__(77)
        var_166 = paddle.tensor.manipulation.gather(var_10, var_165)
        var_167 = var_1.__getitem__(78)
        var_168 = paddle.tensor.manipulation.gather(var_10, var_167)
        var_169 = var_1.__getitem__(79)
        var_170 = paddle.tensor.manipulation.gather(var_10, var_169)
        var_171 = var_1.__getitem__(80)
        var_172 = paddle.tensor.manipulation.gather(var_10, var_171)
        var_173 = var_1.__getitem__(81)
        var_174 = paddle.tensor.manipulation.gather(var_10, var_173)
        var_175 = var_1.__getitem__(82)
        var_176 = paddle.tensor.manipulation.gather(var_10, var_175)
        var_177 = var_1.__getitem__(83)
        var_178 = paddle.tensor.manipulation.gather(var_10, var_177)
        var_179 = var_1.__getitem__(84)
        var_180 = paddle.tensor.manipulation.gather(var_10, var_179)
        var_181 = var_1.__getitem__(85)
        var_182 = paddle.tensor.manipulation.gather(var_10, var_181)
        var_183 = var_1.__getitem__(86)
        var_184 = paddle.tensor.manipulation.gather(var_10, var_183)
        var_185 = var_1.__getitem__(87)
        var_186 = paddle.tensor.manipulation.gather(var_10, var_185)
        var_187 = var_1.__getitem__(88)
        var_188 = paddle.tensor.manipulation.gather(var_10, var_187)
        var_189 = var_1.__getitem__(89)
        var_190 = paddle.tensor.manipulation.gather(var_10, var_189)
        var_191 = var_1.__getitem__(90)
        var_192 = paddle.tensor.manipulation.gather(var_10, var_191)
        var_193 = var_1.__getitem__(91)
        var_194 = paddle.tensor.manipulation.gather(var_10, var_193)
        var_195 = var_1.__getitem__(92)
        var_196 = paddle.tensor.manipulation.gather(var_10, var_195)
        var_197 = var_1.__getitem__(93)
        var_198 = paddle.tensor.manipulation.gather(var_10, var_197)
        var_199 = var_1.__getitem__(94)
        var_200 = paddle.tensor.manipulation.gather(var_10, var_199)
        var_201 = var_1.__getitem__(95)
        var_202 = paddle.tensor.manipulation.gather(var_10, var_201)
        var_203 = var_1.__getitem__(96)
        var_204 = paddle.tensor.manipulation.gather(var_10, var_203)
        var_205 = var_1.__getitem__(97)
        var_206 = paddle.tensor.manipulation.gather(var_10, var_205)
        var_207 = var_1.__getitem__(98)
        var_208 = paddle.tensor.manipulation.gather(var_10, var_207)
        var_209 = var_1.__getitem__(99)
        var_210 = paddle.tensor.manipulation.gather(var_10, var_209)
        var_211 = var_1.__getitem__(100)
        var_212 = paddle.tensor.manipulation.gather(var_10, var_211)
        var_213 = var_1.__getitem__(101)
        var_214 = paddle.tensor.manipulation.gather(var_10, var_213)
        var_215 = var_1.__getitem__(102)
        var_216 = paddle.tensor.manipulation.gather(var_10, var_215)
        var_217 = var_1.__getitem__(103)
        var_218 = paddle.tensor.manipulation.gather(var_10, var_217)
        var_219 = var_1.__getitem__(104)
        var_220 = paddle.tensor.manipulation.gather(var_10, var_219)
        var_221 = var_1.__getitem__(105)
        var_222 = paddle.tensor.manipulation.gather(var_10, var_221)
        var_223 = var_1.__getitem__(106)
        var_224 = paddle.tensor.manipulation.gather(var_10, var_223)
        var_225 = var_1.__getitem__(107)
        var_226 = paddle.tensor.manipulation.gather(var_10, var_225)
        var_227 = var_1.__getitem__(108)
        var_228 = paddle.tensor.manipulation.gather(var_10, var_227)
        var_229 = var_1.__getitem__(109)
        var_230 = paddle.tensor.manipulation.gather(var_10, var_229)
        var_231 = var_1.__getitem__(110)
        var_232 = paddle.tensor.manipulation.gather(var_10, var_231)
        var_233 = var_1.__getitem__(111)
        var_234 = paddle.tensor.manipulation.gather(var_10, var_233)
        var_235 = var_1.__getitem__(112)
        var_236 = paddle.tensor.manipulation.gather(var_10, var_235)
        var_237 = var_1.__getitem__(113)
        var_238 = paddle.tensor.manipulation.gather(var_10, var_237)
        var_239 = var_1.__getitem__(114)
        var_240 = paddle.tensor.manipulation.gather(var_10, var_239)
        var_241 = var_1.__getitem__(115)
        var_242 = paddle.tensor.manipulation.gather(var_10, var_241)
        var_243 = var_1.__getitem__(116)
        var_244 = paddle.tensor.manipulation.gather(var_10, var_243)
        var_245 = var_1.__getitem__(117)
        var_246 = paddle.tensor.manipulation.gather(var_10, var_245)
        var_247 = var_1.__getitem__(118)
        var_248 = paddle.tensor.manipulation.gather(var_10, var_247)
        var_249 = var_1.__getitem__(119)
        var_250 = paddle.tensor.manipulation.gather(var_10, var_249)
        var_251 = var_1.__getitem__(120)
        var_252 = paddle.tensor.manipulation.gather(var_10, var_251)
        var_253 = var_1.__getitem__(121)
        var_254 = paddle.tensor.manipulation.gather(var_10, var_253)
        var_255 = var_1.__getitem__(122)
        var_256 = paddle.tensor.manipulation.gather(var_10, var_255)
        var_257 = var_1.__getitem__(123)
        var_258 = paddle.tensor.manipulation.gather(var_10, var_257)
        var_259 = var_1.__getitem__(124)
        var_260 = paddle.tensor.manipulation.gather(var_10, var_259)
        var_261 = var_1.__getitem__(125)
        var_262 = paddle.tensor.manipulation.gather(var_10, var_261)
        var_263 = var_1.__getitem__(126)
        var_264 = paddle.tensor.manipulation.gather(var_10, var_263)
        var_265 = var_1.__getitem__(127)
        var_266 = paddle.tensor.manipulation.gather(var_10, var_265)
        var_267 = var_1.__getitem__(128)
        var_268 = paddle.tensor.manipulation.gather(var_10, var_267)
        var_269 = var_1.__getitem__(129)
        var_270 = paddle.tensor.manipulation.gather(var_10, var_269)
        var_271 = var_1.__getitem__(130)
        var_272 = paddle.tensor.manipulation.gather(var_10, var_271)
        var_273 = var_1.__getitem__(131)
        var_274 = paddle.tensor.manipulation.gather(var_10, var_273)
        var_275 = var_1.__getitem__(132)
        var_276 = paddle.tensor.manipulation.gather(var_10, var_275)
        var_277 = var_1.__getitem__(133)
        var_278 = paddle.tensor.manipulation.gather(var_10, var_277)
        var_279 = var_1.__getitem__(134)
        var_280 = paddle.tensor.manipulation.gather(var_10, var_279)
        var_281 = var_1.__getitem__(135)
        var_282 = paddle.tensor.manipulation.gather(var_10, var_281)
        var_283 = var_1.__getitem__(136)
        var_284 = paddle.tensor.manipulation.gather(var_10, var_283)
        var_285 = var_1.__getitem__(137)
        var_286 = paddle.tensor.manipulation.gather(var_10, var_285)
        var_287 = var_1.__getitem__(138)
        var_288 = paddle.tensor.manipulation.gather(var_10, var_287)
        var_289 = var_1.__getitem__(139)
        var_290 = paddle.tensor.manipulation.gather(var_10, var_289)
        var_291 = var_1.__getitem__(140)
        var_292 = paddle.tensor.manipulation.gather(var_10, var_291)
        var_293 = var_1.__getitem__(141)
        var_294 = paddle.tensor.manipulation.gather(var_10, var_293)
        var_295 = var_1.__getitem__(142)
        var_296 = paddle.tensor.manipulation.gather(var_10, var_295)
        var_297 = var_1.__getitem__(143)
        var_298 = paddle.tensor.manipulation.gather(var_10, var_297)
        var_299 = var_1.__getitem__(144)
        var_300 = paddle.tensor.manipulation.gather(var_10, var_299)
        var_301 = var_1.__getitem__(145)
        var_302 = paddle.tensor.manipulation.gather(var_10, var_301)
        var_303 = var_1.__getitem__(146)
        var_304 = paddle.tensor.manipulation.gather(var_10, var_303)
        var_305 = var_1.__getitem__(147)
        var_306 = paddle.tensor.manipulation.gather(var_10, var_305)
        var_307 = var_1.__getitem__(148)
        var_308 = paddle.tensor.manipulation.gather(var_10, var_307)
        var_309 = var_1.__getitem__(149)
        var_310 = paddle.tensor.manipulation.gather(var_10, var_309)
        var_311 = var_1.__getitem__(150)
        var_312 = paddle.tensor.manipulation.gather(var_10, var_311)
        var_313 = var_1.__getitem__(151)
        var_314 = paddle.tensor.manipulation.gather(var_10, var_313)
        var_315 = var_1.__getitem__(152)
        var_316 = paddle.tensor.manipulation.gather(var_10, var_315)
        var_317 = var_1.__getitem__(153)
        var_318 = paddle.tensor.manipulation.gather(var_10, var_317)
        var_319 = var_1.__getitem__(154)
        var_320 = paddle.tensor.manipulation.gather(var_10, var_319)
        var_321 = var_1.__getitem__(155)
        var_322 = paddle.tensor.manipulation.gather(var_10, var_321)
        var_323 = var_1.__getitem__(156)
        var_324 = paddle.tensor.manipulation.gather(var_10, var_323)
        var_325 = var_1.__getitem__(157)
        var_326 = paddle.tensor.manipulation.gather(var_10, var_325)
        var_327 = var_1.__getitem__(158)
        var_328 = paddle.tensor.manipulation.gather(var_10, var_327)
        var_329 = var_1.__getitem__(159)
        var_330 = paddle.tensor.manipulation.gather(var_10, var_329)
        var_331 = var_1.__getitem__(160)
        var_332 = paddle.tensor.manipulation.gather(var_10, var_331)
        var_333 = var_1.__getitem__(161)
        var_334 = paddle.tensor.manipulation.gather(var_10, var_333)
        var_335 = var_1.__getitem__(162)
        var_336 = paddle.tensor.manipulation.gather(var_10, var_335)
        var_337 = var_1.__getitem__(163)
        var_338 = paddle.tensor.manipulation.gather(var_10, var_337)
        var_339 = var_1.__getitem__(164)
        var_340 = paddle.tensor.manipulation.gather(var_10, var_339)
        var_341 = var_1.__getitem__(165)
        var_342 = paddle.tensor.manipulation.gather(var_10, var_341)
        var_343 = var_1.__getitem__(166)
        var_344 = paddle.tensor.manipulation.gather(var_10, var_343)
        var_345 = var_1.__getitem__(167)
        var_346 = paddle.tensor.manipulation.gather(var_10, var_345)
        var_347 = var_1.__getitem__(168)
        var_348 = paddle.tensor.manipulation.gather(var_10, var_347)
        var_349 = var_1.__getitem__(169)
        var_350 = paddle.tensor.manipulation.gather(var_10, var_349)
        var_351 = var_1.__getitem__(170)
        var_352 = paddle.tensor.manipulation.gather(var_10, var_351)
        var_353 = var_1.__getitem__(171)
        var_354 = paddle.tensor.manipulation.gather(var_10, var_353)
        var_355 = var_1.__getitem__(172)
        var_356 = paddle.tensor.manipulation.gather(var_10, var_355)
        var_357 = var_1.__getitem__(173)
        var_358 = paddle.tensor.manipulation.gather(var_10, var_357)
        var_359 = var_1.__getitem__(174)
        var_360 = paddle.tensor.manipulation.gather(var_10, var_359)
        var_361 = var_1.__getitem__(175)
        var_362 = paddle.tensor.manipulation.gather(var_10, var_361)
        var_363 = var_1.__getitem__(176)
        var_364 = paddle.tensor.manipulation.gather(var_10, var_363)
        var_365 = var_1.__getitem__(177)
        var_366 = paddle.tensor.manipulation.gather(var_10, var_365)
        var_367 = var_1.__getitem__(178)
        var_368 = paddle.tensor.manipulation.gather(var_10, var_367)
        var_369 = var_1.__getitem__(179)
        var_370 = paddle.tensor.manipulation.gather(var_10, var_369)
        var_371 = var_1.__getitem__(180)
        var_372 = paddle.tensor.manipulation.gather(var_10, var_371)
        var_373 = var_1.__getitem__(181)
        var_374 = paddle.tensor.manipulation.gather(var_10, var_373)
        var_375 = var_1.__getitem__(182)
        var_376 = paddle.tensor.manipulation.gather(var_10, var_375)
        var_377 = var_1.__getitem__(183)
        var_378 = paddle.tensor.manipulation.gather(var_10, var_377)
        var_379 = var_1.__getitem__(184)
        var_380 = paddle.tensor.manipulation.gather(var_10, var_379)
        var_381 = var_1.__getitem__(185)
        var_382 = paddle.tensor.manipulation.gather(var_10, var_381)
        var_383 = var_1.__getitem__(186)
        var_384 = paddle.tensor.manipulation.gather(var_10, var_383)
        var_385 = var_1.__getitem__(187)
        var_386 = paddle.tensor.manipulation.gather(var_10, var_385)
        var_387 = var_1.__getitem__(188)
        var_388 = paddle.tensor.manipulation.gather(var_10, var_387)
        var_389 = var_1.__getitem__(189)
        var_390 = paddle.tensor.manipulation.gather(var_10, var_389)
        var_391 = var_1.__getitem__(190)
        var_392 = paddle.tensor.manipulation.gather(var_10, var_391)
        var_393 = var_1.__getitem__(191)
        var_394 = paddle.tensor.manipulation.gather(var_10, var_393)
        var_395 = var_1.__getitem__(192)
        var_396 = paddle.tensor.manipulation.gather(var_10, var_395)
        var_397 = var_1.__getitem__(193)
        var_398 = paddle.tensor.manipulation.gather(var_10, var_397)
        var_399 = var_1.__getitem__(194)
        var_400 = paddle.tensor.manipulation.gather(var_10, var_399)
        var_401 = var_1.__getitem__(195)
        var_402 = paddle.tensor.manipulation.gather(var_10, var_401)
        var_403 = paddle.tensor.manipulation.concat([var_12, var_14, var_16, var_18, var_20, var_22, var_24, var_26, var_28, var_30, var_32, var_34, var_36, var_38, var_40, var_42, var_44, var_46, var_48, var_50, var_52, var_54, var_56, var_58, var_60, var_62, var_64, var_66, var_68, var_70, var_72, var_74, var_76, var_78, var_80, var_82, var_84, var_86, var_88, var_90, var_92, var_94, var_96, var_98, var_100, var_102, var_104, var_106, var_108, var_110, var_112, var_114, var_116, var_118, var_120, var_122, var_124, var_126, var_128, var_130, var_132, var_134, var_136, var_138, var_140, var_142, var_144, var_146, var_148, var_150, var_152, var_154, var_156, var_158, var_160, var_162, var_164, var_166, var_168, var_170, var_172, var_174, var_176, var_178, var_180, var_182, var_184, var_186, var_188, var_190, var_192, var_194, var_196, var_198, var_200, var_202, var_204, var_206, var_208, var_210, var_212, var_214, var_216, var_218, var_220, var_222, var_224, var_226, var_228, var_230, var_232, var_234, var_236, var_238, var_240, var_242, var_244, var_246, var_248, var_250, var_252, var_254, var_256, var_258, var_260, var_262, var_264, var_266, var_268, var_270, var_272, var_274, var_276, var_278, var_280, var_282, var_284, var_286, var_288, var_290, var_292, var_294, var_296, var_298, var_300, var_302, var_304, var_306, var_308, var_310, var_312, var_314, var_316, var_318, var_320, var_322, var_324, var_326, var_328, var_330, var_332, var_334, var_336, var_338, var_340, var_342, var_344, var_346, var_348, var_350, var_352, var_354, var_356, var_358, var_360, var_362, var_364, var_366, var_368, var_370, var_372, var_374, var_376, var_378, var_380, var_382, var_384, var_386, var_388, var_390, var_392, var_394, var_396, var_398, var_400, var_402])
        var_404 = paddle.tensor.linalg.transpose(var_403, (1, 0,))
        var_405 = var_404.reshape((0, 196, 196,))
        return var_6, var_9, var_405, var_8


def create_tensor_inputs():
    inputs = (
        paddle.rand(shape=[22, 196, 256], dtype=paddle.float32),
        paddle.randint(low=0, high=10, shape=[196, 196], dtype=paddle.int64),
    )
    return inputs


def create_numpy_inputs():
    inputs = (
        np.random.random(size=[22, 196, 256]).astype('float32'),
        np.random.randint(low=0, high=10, size=[196, 196], dtype='int64'),
    )
    return inputs


class TestLayer(unittest.TestCase):
    def setUp(self):
        self.inputs = create_tensor_inputs()
        self.net = LayerCase()
    def train(self, net, to_static, with_prim=False, with_cinn=False):
        if to_static:
            paddle.set_flags({'FLAGS_prim_all': with_prim})
            if with_cinn:
                build_strategy = paddle.static.BuildStrategy()
                build_strategy.build_cinn_pass = True
                net = paddle.jit.to_static(net, build_strategy=build_strategy, full_graph=True)
            else:
                net = paddle.jit.to_static(net, full_graph=True)
        paddle.seed(123)
        outs = net(*self.inputs)
        return outs
    def test_ast_prim_cinn(self):
        st_out = self.train(self.net, to_static=True)
        cinn_out = self.train(self.net, to_static=True, with_prim=True, with_cinn=True)
        for st, cinn in zip(paddle.utils.flatten(st_out), paddle.utils.flatten(cinn_out)):
            np.testing.assert_allclose(st.numpy(), cinn.numpy(), atol=1e-8)


if __name__ == '__main__':
    unittest.main()