import layercase.perf245.Clas_cases.CSWinTransformer_CSWinTransformer_base_384
import layercase.perf245.Clas_cases.DLA_DLA102
import layercase.perf245.Clas_cases.DeiT_DeiT_tiny_distilled_patch16_224
import layercase.perf245.Clas_cases.DeiT_DeiT_tiny_patch16_224
import layercase.perf245.Clas_cases.Distillation_PPLCNet_x2_5_ssld
import layercase.perf245.Clas_cases.Distillation_resnet34_distill_resnet18_afd
import layercase.perf245.Clas_cases.EfficientNet_EfficientNetB0
