import layercase.sublayer1000.Det_cases.vitdet_ppyoloe_vit_base_csppan_cae_36e_coco./SIR_6
import layercase.sublayer1000.Det_cases.vitdet_ppyoloe_vit_base_csppan_cae_36e_coco./SIR_140
import layercase.sublayer1000.Det_cases.vitdet_ppyoloe_vit_base_csppan_cae_36e_coco./SIR_135
