import layercase.Clas_cases.CSWinTransformer_CSWinTransformer_base_384.SIR_116
import layercase.Clas_cases.CSWinTransformer_CSWinTransformer_base_384.SIR_233
import layercase.Clas_cases.CSWinTransformer_CSWinTransformer_base_384.SIR_178
import layercase.Clas_cases.CSWinTransformer_CSWinTransformer_base_384.SIR_283
