import layercase.Det_cases.sparse_rcnn_sparse_rcnn_r50_fpn_3x_pro300_coco.SIR_34
import layercase.Det_cases.sparse_rcnn_sparse_rcnn_r50_fpn_3x_pro300_coco.SIR_36
import layercase.Det_cases.sparse_rcnn_sparse_rcnn_r50_fpn_3x_pro300_coco.SIR_62
import layercase.Det_cases.sparse_rcnn_sparse_rcnn_r50_fpn_3x_pro300_coco.SIR_61
