import layercase.sublayer160.Clas_cases.EfficientNet_EfficientNetB0.SIR_116
import layercase.sublayer160.Clas_cases.EfficientNet_EfficientNetB0.SIR_202
import layercase.sublayer160.Clas_cases.EfficientNet_EfficientNetB0.SIR_128
import layercase.sublayer160.Clas_cases.EfficientNet_EfficientNetB0.SIR_96
