import layercase.sublayer1000.Det_cases.cascade_rcnn_cascade_mask_rcnn_r50_vd_fpn_ssld_1x_coco.SIR_85
import layercase.sublayer1000.Det_cases.cascade_rcnn_cascade_mask_rcnn_r50_vd_fpn_ssld_1x_coco.SIR_145
import layercase.sublayer1000.Det_cases.cascade_rcnn_cascade_mask_rcnn_r50_vd_fpn_ssld_1x_coco.SIR_89
import layercase.sublayer1000.Det_cases.cascade_rcnn_cascade_mask_rcnn_r50_vd_fpn_ssld_1x_coco.SIR_143
import layercase.sublayer1000.Det_cases.cascade_rcnn_cascade_mask_rcnn_r50_vd_fpn_ssld_1x_coco.SIR_148
